### ISSUE TITLE
JSON Decode Error

### ISSUE THREAD

**Issue by ryanmccann1024** [SDNNetSim/SDON_simulator#68]
---
name: Bug report
about: Create a report to help us improve
title: JSON Decode Error
labels: bug, unity cluster
assignees: Me, Myself, and I
---

**Describe the bug**  
When submitting many jobs (>50) on the Unity cluster as an array of batch jobs, it seems some jobs are reading files while others are writing, leading me to believe the file is not properly locked when any given job is trying to access the bandwidth file object. This leads to some jobs failing and others run successfully.

**Steps to reproduce**  
List the steps to reproduce the bug.
1. Submit greater than 50 jobs to the unity cluster as a batch array

**Expected behavior**  
All jobs should run without a file decoding error when starting a simulation.

**System information (please complete the following information):**  
- OS Version: Ubuntu
- Programming Language Version: Python 3.11

**Additional context**
Error code is the following:
```

Custom environment 'SimEnv' registered for algorithm 'ppo' in Stable Baselines 3 and Gymnasium RL library.
Traceback (most recent call last):
  File "/work/pi_vinod_vokkarane_uml_edu/git/SDON_simulator/run_rl_sim.py", line 488, in <module>
    run_rl_sim()
  File "/work/pi_vinod_vokkarane_uml_edu/git/SDON_simulator/run_rl_sim.py", line 482, in run_rl_sim
    env = SimEnv(render_mode=None, custom_callback=callback, sim_dict=setup_rl_sim())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/pi_vinod_vokkarane_uml_edu/git/SDON_simulator/run_rl_sim.py", line 56, in __init__
    self.reset(options={'save_sim': False})
  File "/work/pi_vinod_vokkarane_uml_edu/git/SDON_simulator/run_rl_sim.py", line 369, in reset
    self.setup()
  File "/work/pi_vinod_vokkarane_uml_edu/git/SDON_simulator/run_rl_sim.py", line 329, in setup
    self._create_input()
  File "/work/pi_vinod_vokkarane_uml_edu/git/SDON_simulator/run_rl_sim.py", line 295, in _create_input
    self.sim_props = create_input(base_fp=base_fp, engine_props=self.sim_dict)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/pi_vinod_vokkarane_uml_edu/git/SDON_simulator/helper_scripts/setup_helpers.py", line 24, in create_input
    engine_props['mod_per_bw'] = json.load(file_object)
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/modules/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/python-3.11.0-5d5wu4shk5euvpumjljr4evlrzmauzb7/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/modules/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/python-3.11.0-5d5wu4shk5euvpumjljr4evlrzmauzb7/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/modules/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/python-3.11.0-5d5wu4shk5euvpumjljr4evlrzmauzb7/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/modules/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/python-3.11.0-5d5wu4shk5euvpumjljr4evlrzmauzb7/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error running Python script for job 42
```

**Comment by ryanmccann1024** [comment]
This is still an issue even with 20 batch jobs. I plan to fix this over the summer.

**Comment by ryanmccann1024** [comment]
Put a sleep before job submission, no more identical start times.
